-- MySQL Script generated by MySQL Workbench
-- Sat May  8 13:53:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo` (
  `idmodelo` INT NOT NULL,
  `marca_id` INT NOT NULL,
  PRIMARY KEY (`idmodelo`),
  INDEX `fk_modelo_marca1_idx` (`marca_id` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `mydb`.`marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`puesto` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bien` (
  `id` INT NOT NULL,
  `puesto_id` INT NOT NULL,
  `marca_id` INT NOT NULL,
  `modelo_id` INT NOT NULL,
  `denominacion` VARCHAR(45) NULL,
  `codigo_patrimonial` VARCHAR(45) NOT NULL,
  `codigo_ambiente` VARCHAR(45) NULL,
  `codigo_inventario` VARCHAR(8) NULL,
  `fecha_inventario` VARCHAR(4) NULL,
  `serie` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bienes_marca1_idx` (`marca_id` ASC) VISIBLE,
  INDEX `fk_bienes_modelo1_idx` (`modelo_id` ASC) VISIBLE,
  UNIQUE INDEX `codigo_patrimonial_UNIQUE` (`codigo_patrimonial` ASC) VISIBLE,
  INDEX `fk_bien_puesto1_idx` (`puesto_id` ASC) VISIBLE,
  CONSTRAINT `fk_bienes_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `mydb`.`marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bienes_modelo1`
    FOREIGN KEY (`modelo_id`)
    REFERENCES `mydb`.`modelo` (`idmodelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bien_puesto1`
    FOREIGN KEY (`puesto_id`)
    REFERENCES `mydb`.`puesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_orden` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`motivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`motivo` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_orden` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`origen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`origen` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rol_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rol_usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL,
  `rol_usuario_id` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `bestado` CHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_rol_usuario1_idx` (`rol_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol_usuario1`
    FOREIGN KEY (`rol_usuario_id`)
    REFERENCES `mydb`.`rol_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden` (
  `id` INT NOT NULL,
  `tipo_orden_id` INT NOT NULL,
  `motivo_id` INT NOT NULL,
  `estado_orden_id` INT NOT NULL,
  `origen_id` INT NOT NULL,
  `destino` VARCHAR(45) NULL,
  `fecha_salida_prevista` DATE NULL,
  `fecha_retorno_prevista` DATE NULL,
  `comisionado` VARCHAR(45) NULL,
  `comisionado_dni` VARCHAR(45) NULL,
  `comisionado_area` VARCHAR(45) NULL,
  `autoriza` VARCHAR(45) NULL,
  `autoriza_dni` VARCHAR(45) NULL,
  `autoriza_area` VARCHAR(45) NULL,
  `accesorio` VARCHAR(45) NULL,
  `observacion` VARCHAR(45) NULL,
  `fecha_salida` DATETIME NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orden_tipo_orden_idx` (`tipo_orden_id` ASC) VISIBLE,
  INDEX `fk_orden_motivo1_idx` (`motivo_id` ASC) VISIBLE,
  INDEX `fk_orden_estado_orden1_idx` (`estado_orden_id` ASC) VISIBLE,
  INDEX `fk_orden_origen1_idx` (`origen_id` ASC) VISIBLE,
  INDEX `fk_orden_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_orden_tipo_orden`
    FOREIGN KEY (`tipo_orden_id`)
    REFERENCES `mydb`.`tipo_orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_motivo1`
    FOREIGN KEY (`motivo_id`)
    REFERENCES `mydb`.`motivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_estado_orden1`
    FOREIGN KEY (`estado_orden_id`)
    REFERENCES `mydb`.`estado_orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_origen1`
    FOREIGN KEY (`origen_id`)
    REFERENCES `mydb`.`origen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personal` (
  `id` INT NOT NULL,
  `puesto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personal_puesto1_idx` (`puesto_id` ASC) VISIBLE,
  CONSTRAINT `fk_personal_puesto1`
    FOREIGN KEY (`puesto_id`)
    REFERENCES `mydb`.`puesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rol_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rol_usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden_detalle` (
  `id` INT NOT NULL,
  `orden_id` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `denominacion` VARCHAR(45) NULL,
  `codigo_patrimonial` VARCHAR(45) NULL,
  `codigo_ambiente` VARCHAR(45) NULL,
  `codigo_inventario` VARCHAR(45) NULL,
  `serie` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `retorna` CHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orden_detalle_orden1_idx` (`orden_id` ASC) VISIBLE,
  CONSTRAINT `fk_orden_detalle_orden1`
    FOREIGN KEY (`orden_id`)
    REFERENCES `mydb`.`orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden_firma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden_firma` (
  `id` INT NOT NULL,
  `orden_id` INT NOT NULL,
  `cargo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `estado` CHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orden_firma_orden1_idx` (`orden_id` ASC) VISIBLE,
  CONSTRAINT `fk_orden_firma_orden1`
    FOREIGN KEY (`orden_id`)
    REFERENCES `mydb`.`orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`configuracion_firma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`configuracion_firma` (
  `id` INT NOT NULL,
  `personal_id` INT NOT NULL,
  `cargo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `bestado` CHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_configuracion_firma_personal1_idx` (`personal_id` ASC) VISIBLE,
  CONSTRAINT `fk_configuracion_firma_personal1`
    FOREIGN KEY (`personal_id`)
    REFERENCES `mydb`.`personal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden_retorno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden_retorno` (
  `id` INT NOT NULL,
  `orden_id` INT NOT NULL,
  `comisionado` VARCHAR(45) NULL,
  `comisionado_dni` VARCHAR(45) NULL,
  `comisionado_area` VARCHAR(45) NULL,
  `asignado` VARCHAR(45) NULL,
  `asignado_dni` VARCHAR(45) NULL,
  `asignado_area` VARCHAR(45) NULL,
  `fecha_retorno` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orden_retorno_orden1_idx` (`orden_id` ASC) VISIBLE,
  CONSTRAINT `fk_orden_retorno_orden1`
    FOREIGN KEY (`orden_id`)
    REFERENCES `mydb`.`orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden_retorno_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden_retorno_detalle` (
  `id` INT NOT NULL,
  `orden_retorno_idorden_retorno` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `denominacion` VARCHAR(45) NULL,
  `codigo_patrimonial` VARCHAR(45) NULL,
  `codigo_ambiente` VARCHAR(45) NULL,
  `codigo_inventario` VARCHAR(45) NULL,
  `serie` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `fecha_retorno_prevista` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orden_retorno_detalle_orden_retorno1_idx` (`orden_retorno_idorden_retorno` ASC) VISIBLE,
  CONSTRAINT `fk_orden_retorno_detalle_orden_retorno1`
    FOREIGN KEY (`orden_retorno_idorden_retorno`)
    REFERENCES `mydb`.`orden_retorno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden_retorno_firma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden_retorno_firma` (
  `id` INT NOT NULL,
  `orden_retorno_id` INT NOT NULL,
  `cargo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `estado` CHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orden_retorno_firma_orden_retorno1_idx` (`orden_retorno_id` ASC) VISIBLE,
  CONSTRAINT `fk_orden_retorno_firma_orden_retorno1`
    FOREIGN KEY (`orden_retorno_id`)
    REFERENCES `mydb`.`orden_retorno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
